name: CI

on:
  push:
    # paths:
    #   - '.github/**'
    #   - 'src/**'
    #   - 'test/**'
  pull_request:
    # paths:
    #   - '.github/**'
    #   - 'src/**'
    #   - 'test/**'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18, 20, 22]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm ci

      # - name: Run ESLint
      #   run: npm run lint

      - name: Build Packages
        run: npm run build

      - name: Run Tests
        run: npm test

      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@v1
